name: Deploy
env:
  PACKAGE_S3_BUCKET_NAME : "ci-cd-complete"
  AWS_REGION_NAME        : "ap-south-1"
  DEPLOY_PACKAGE_NAME    : "gsuite-app-$(date +%Y%m%d).zip"
  release_layer          : ${{ format('gsuite-app-$(date +%Y%m%d)-dev', github.head_ref )}}
on:
  push:
    branches:
      - master

jobs:
    ci-cd:
       runs-on: ubuntu-latest

       steps:
         - name: Git clone repository
           uses: actions/checkout@v2

         - name: Install Packages
           run : pip download -r requirements.txt

         - name: Zip the function
           run : zip -r function.zip  ./lambda_function.py

         - name: Create ZIP deployment package
           run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./  -x  *.git*

         - name: Configure AWS Credentials
           uses: aws-actions/configure-aws-credentials@v1
           with:
             aws-access-key-id    : ${{ secrets.BOT_AWS_ACCESS_KEY }}
             aws-secret-access-key: ${{ secrets.BOT_AWS_SECRET_KEY }}
             aws-region           : ${{ env.AWS_REGION_NAME }}

         - name: Copy our Deployment package to S3 bucket
           run : aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.PACKAGE_S3_BUCKET_NAME}}/

         - name: Update the Function Code
           run:
             aws lambda update-function-code --function-name "lambda-deploy"
             --zip-file  fileb://function.zip
