name: Deploy
env:
  PACKAGE_S3_BUCKET_NAME : "ci-cd-complete"
  AWS_REGION_NAME        : "ap-south-1"
  DEPLOY_PACKAGE_NAME    : "gsuite-app-$(date +%Y%m%d).zip"
  release_layer          : ${{ format('gsuite-app-$(date +%Y%m%d)-dev', github.head_ref )}}
on:
  push:
    branches:
      - master

jobs:
    integrate-to-s3:
       runs-on: ubuntu-latest

       steps:
         - name: Git clone repository
           uses: actions/checkout@v2

         - name: Install Packages
           run : pip download -r requirements.txt

         - name: Create ZIP deployment package
           run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./  -x  *.git*

         - name: Configure AWS Credentials
           uses: aws-actions/configure-aws-credentials@v1
           with:
             aws-access-key-id    : ${{ secrets.BOT_AWS_ACCESS_KEY }}
             aws-secret-access-key: ${{ secrets.BOT_AWS_SECRET_KEY }}
             aws-region           : ${{ env.AWS_REGION_NAME }}

         - name: Copy our Deployment package to S3 bucket
           run : aws s3 cp ${{ env.DEPLOY_PACKAGE_NAME }} s3://${{ env.PACKAGE_S3_BUCKET_NAME}}/

    deploy-lambda:
       runs-on: ubuntu-latest
       needs: [integrate-to-s3]

       steps:

         - name: Configure AWS Credentils Again
           uses: aws-actions/configure-aws-credentials@v1
           with:
             aws-access-key-id    : ${{ secrets.BOT_AWS_ACCESS_KEY }}
             aws-secret-access-key: ${{ secrets.BOT_AWS_SECRET_KEY }}
             aws-region           : ${{ env.AWS_REGION_NAME }}

         - name: Setup Python 3.8
           uses: actions/setup-python@v1
           with:
             python-version: 3.8

         - name: Install it in Lambda Layers
           run:
             aws lambda publish-layer-version --layer-name my-layer 
             --description "My Python layer"
             --content S3Bucket="${{ env.PACKAGE_S3_BUCKET_NAME }}",S3Key="${{ env.DEPLOY_PACKAGE_NAME }}"
             --compatible-runtimes python3.6 python3.7 python3.8
